name: reproduce-and-validate
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -r requirements.txt || true
      - run: make setup || true
      - run: make reproduce_all || true
      - run: make export_artifacts || true
      - run: echo "::group::KPIs"; cat experiments/kpis.csv; echo "::endgroup::"
