name: semcrypto
on: [push]
jobs:
  t:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          python semantic_demo.py || true
          python tests_semantic_crypto.py
