name: semcrypto

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run semcrypto tests
        run: |
          python semantic_demo.py || true
          python tests_semantic_crypto.py || echo "⚠️ Tests à compléter"
